// src/components/features/university/UniversityDetailPage/components/sidebar/application-card.tsx
import { Calendar, Clock } from "lucide-react"
import { Card, CardContent } from "@/components/ui/react/card"
import { Button } from "@/components/ui/react/button"
import type { SidebarCardProps } from "../../types"

export default function ApplicationCard({ university, lang }: SidebarCardProps) {
  return (
    <Card className="border-none shadow-md overflow-hidden">
      <div className="bg-gradient-to-r from-blue-600 to-blue-700 p-4 text-white">
        <h3 className="font-bold text-lg">Apply Now</h3>
        <p className="text-white/80 text-sm mt-1">
          Start your application to {university.name}
        </p>
      </div>
      <CardContent className="p-4">
        <div className="space-y-4">
          <div className="flex justify-between items-center p-3 bg-blue-50 rounded-lg">
            <div className="flex items-center gap-2">
              <Calendar className="h-5 w-5 text-blue-600" />
              <span className="text-sm font-medium">Application Deadline</span>
            </div>
            <span className="text-sm font-bold">June 30, 2023</span>
          </div>
          
          <div className="flex justify-between items-center p-3 bg-blue-50 rounded-lg">
            <div className="flex items-center gap-2">
              <Clock className="h-5 w-5 text-blue-600" />
              <span className="text-sm font-medium">Processing Time</span>
            </div>
            <span className="text-sm font-bold">4-6 weeks</span>
          </div>
          
          <div className="bg-slate-50 p-3 rounded-lg">
            <p className="text-sm text-slate-600">
              Application Fee: <span className="font-bold text-slate-800">$50 - $100</span>
            </p>
          </div>
          
          <Button className="w-full bg-blue-600 hover:bg-blue-700">
            Apply Online
          </Button>
          
          <p className="text-xs text-slate-500 text-center">
            For more information about the application process, please visit the university's official website.
          </p>
        </div>
      </CardContent>
    </Card>
  )
}

// src/components/features/university/UniversityDetailPage/components/sidebar/ApplicationCard.svelte
<script lang="ts">
  import { Calendar, Clock } from "lucide-svelte";
  import { Card, CardContent } from "@/components/ui/svelte";
  import { Button } from "@/components/ui/svelte";
  import type { University } from "@/types/university";
  import type { Lang } from "@/i18n/langUtils";
  import type { UniversityDetailTranslations } from "@/i18n/features/university/universityDetail";

  export let university: University;
  export let lang: Lang;
  export let t: UniversityDetailTranslations;
  
  $: subtitle = t.application.subtitle.replace('{university}', university.name);
</script>

<Card class="border-none shadow-md overflow-hidden">
  <div class="bg-gradient-to-r from-blue-600 to-blue-700 p-4 text-white">
    <h3 class="font-bold text-lg">{t.application.title}</h3>
    <p class="text-white/80 text-sm mt-1">
      {subtitle}
    </p>
  </div>
  <CardContent class="p-4">
    <div class="space-y-4">
      <div class="flex justify-between items-center p-3 bg-blue-50 rounded-lg">
        <div class="flex items-center gap-2">
          <Calendar class="h-5 w-5 text-blue-600" />
          <span class="text-sm font-medium">{t.application.deadline}</span>
        </div>
        <span class="text-sm font-bold">June 30, 2023</span>
      </div>
      
      <div class="flex justify-between items-center p-3 bg-blue-50 rounded-lg">
        <div class="flex items-center gap-2">
          <Clock class="h-5 w-5 text-blue-600" />
          <span class="text-sm font-medium">{t.application.processingTime}</span>
        </div>
        <span class="text-sm font-bold">4-6 weeks</span>
      </div>
      
      <div class="bg-slate-50 p-3 rounded-lg">
        <p class="text-sm text-slate-600">
          {t.application.applicationFee} <span class="font-bold text-slate-800">$50 - $100</span>
        </p>
      </div>
      
      <Button class="w-full bg-blue-600 hover:bg-blue-700">
        {t.application.applyButton}
      </Button>
      
      <p class="text-xs text-slate-500 text-center">
        {t.application.moreInfo}
      </p>
    </div>
  </CardContent>
</Card>
