// src/components/features/university/UniversityDetailPage/components/sidebar/ContactCard.svelte
<script lang="ts">
  import { MapPin, Mail, Phone } from "lucide-svelte";
  import { Card, CardContent } from "@/components/ui/svelte";
  import type { University } from "@/types/university";
  import type { Lang } from "@/i18n/langUtils";

  export let university: University;
  export let lang: Lang;
</script>

<Card class="border-none shadow-md overflow-hidden">
  <CardContent class="p-5">
    <h3 class="font-semibold text-lg mb-4">Contact Information</h3>
    
    <div class="space-y-3">
      {#if university.city}
        <div class="flex items-start gap-3">
          <div class="shrink-0 mt-1">
            <MapPin class="h-5 w-5 text-blue-600" />
          </div>
          <div>
            <p class="text-gray-800">{university.city}</p>
          </div>
        </div>
      {/if}
      
      <div class="flex items-start gap-3">
        <div class="shrink-0 mt-1">
          <Mail class="h-5 w-5 text-blue-600" />
        </div>
        <div>
          <a href="mailto:info@{university.name.toLowerCase().replace(/\s+/g, '')}.edu" class="text-blue-600 hover:underline">
            info@{university.name.toLowerCase().replace(/\s+/g, '')}.edu
          </a>
        </div>
      </div>
      
      <div class="flex items-start gap-3">
        <div class="shrink-0 mt-1">
          <Phone class="h-5 w-5 text-blue-600" />
        </div>
        <div>
          <a href="tel:+1234567890" class="text-blue-600 hover:underline">
            +1 (234) 567-890
          </a>
        </div>
      </div>
    </div>
  </CardContent>
</Card>

// src/components/features/university/UniversityDetailPage/components/sidebar/contact-card.tsx
import { MapPin, Mail, Phone } from "lucide-react"
import { Card, CardContent } from "@/components/ui/react/card"
import { Button } from "@/components/ui/react/button"
import type { SidebarCardProps } from "../../types"

export default function ContactCard({ university, lang }: SidebarCardProps) {
  return (
    <Card className="border-none shadow-md overflow-hidden">
      <CardContent className="p-6">
        <div className="flex gap-3">
          <div className="flex-shrink-0 mt-1">
            <MapPin className="h-6 w-6 text-blue-600" />
          </div>
          <div>
            <h3 className="font-medium text-slate-800 text-lg">Contact Information</h3>
            <p className="text-slate-600 mt-2">
              Get in touch with {university.name} for more information
            </p>
            <div className="mt-4 space-y-3">
              <Button className="w-full bg-blue-600 hover:bg-blue-700">
                Contact University
              </Button>
              <div className="flex items-center gap-2 text-slate-600">
                <MapPin className="h-4 w-4" />
                <span>
                  {typeof university.location === 'object' 
                    ? `${university.location.city || ''}, ${university.location.country || ''}` 
                    : university.city || ''}
                </span>
              </div>
              <div className="flex items-center gap-2 text-slate-600">
                <Mail className="h-4 w-4" />
                <span>admissions@{university.name.toLowerCase().replace(/\s+/g, '')}.edu</span>
              </div>
              <div className="flex items-center gap-2 text-slate-600">
                <Phone className="h-4 w-4" />
                <span>+1 (123) 456-7890</span>
              </div>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
