// src/components/features/university/UniversityPage/components/MobileFilters.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { Button } from "../../../../../components/ui/svelte";
  import { Filter, X } from 'lucide-svelte';
  import { fade, fly } from 'svelte/transition';
  import { cubicOut } from 'svelte/easing';
  import type { Filters } from '../lib/data';
  import Sidebar from './sidebar/Sidebar.svelte';

  export let filters: Filters;
  export let cities: string[] = [];
  export let isOpen = false;
  
  const dispatch = createEventDispatcher<{
    change: { key: keyof Filters; value: string };
    reset: void;
    openStateChange: boolean;
  }>();
  
  function handleChange(event: CustomEvent<{ key: keyof Filters; value: string }>) {
    dispatch('change', event.detail);
  }
  
  function handleReset() {
    dispatch('reset');
  }
  
  function toggleSheet() {
    isOpen = !isOpen;
    dispatch('openStateChange', isOpen);
  }
</script>

<div class="flex items-center justify-between md:hidden">
  <h1 class="text-2xl font-bold">Universities</h1>
  <Button variant="outline" size="icon" on:click={toggleSheet}>
    <Filter class="h-4 w-4" />
    <span class="sr-only">Filter</span>
  </Button>
</div>

{#if isOpen}
  <!-- Backdrop -->
  <div 
    class="fixed inset-0 z-50 bg-black/50" 
    on:click={toggleSheet}
    transition:fade={{ duration: 200, easing: cubicOut }}
  ></div>
  
  <!-- Sidebar -->
  <div 
    class="fixed left-0 top-0 z-50 h-full w-[300px] sm:w-[350px] bg-white shadow-lg"
    transition:fly={{ x: -350, duration: 300, opacity: 1, easing: cubicOut }}
  >
    <div class="flex items-center justify-between p-4 border-b">
      <h2 class="font-semibold">Filters</h2>
      <Button variant="ghost" size="icon" on:click={toggleSheet} class="opacity-70 hover:opacity-100">
        <X class="h-4 w-4" />
      </Button>
    </div>
    <div class="p-4 overflow-y-auto h-[calc(100vh-60px)]">
      <Sidebar 
        {filters} 
        {cities} 
        on:change={handleChange} 
        on:reset={handleReset} 
      />
    </div>
  </div>
{/if}

// src/components/features/university/UniversityPage/components/mobile-filters.tsx
"use client"

import { Filter } from "lucide-react"
import { Button } from "@/components/ui/react/button"
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/react/sheet"
import { Sidebar } from "./sidebar/sidebar"
import { educationTypes, rankingRanges, type Filters } from "../lib/data"

interface MobileFiltersProps {
  filters: Filters
  onChange: (key: keyof Filters, value: string) => void
  onReset: () => void
  cities?: string[]
}

export function MobileFilters({ filters, onChange, onReset, cities = [] }: MobileFiltersProps) {
  return (
    <div className="flex items-center justify-between md:hidden">
      <h1 className="text-2xl font-bold">Universities</h1>
      <Sheet>
        <SheetTrigger asChild>
          <Button variant="outline" size="icon">
            <Filter className="h-4 w-4" />
            <span className="sr-only">Filter</span>
          </Button>
        </SheetTrigger>
        <SheetContent side="left" className="w-[300px] sm:w-[350px]">
          <div className="py-4">
            <Sidebar filters={filters} onChange={onChange} onReset={onReset} />
          </div>
        </SheetContent>
      </Sheet>
    </div>
  )
}
