// src/components/features/university/UniversityPageSvelte/components/MobileFilters.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { Button } from "../../../../../components/ui/svelte";
  import { Sliders } from 'lucide-svelte';
  import type { Filters } from '../lib/data';

  export let filters: Filters;
  
  const dispatch = createEventDispatcher<{
    change: { key: keyof Filters; value: string };
    reset: void;
  }>();
  
  function handleChange(key: keyof Filters, value: string) {
    dispatch('change', { key, value });
  }
  
  function handleReset() {
    dispatch('reset');
  }
</script>

<div class="flex items-center justify-between gap-4 p-4 rounded-lg border">
  <div class="flex items-center gap-2">
    <Sliders class="h-4 w-4 text-muted-foreground" />
    <span class="text-sm font-medium">Filter</span>
  </div>
  
  <div class="flex items-center gap-2">
    <Button 
      variant="outline" 
      size="sm" 
      on:click={handleReset}
    >
      Reset
    </Button>
    <Button 
      variant="default" 
      size="sm" 
      on:click={() => {/* Open full screen filter modal */}}
    >
      All Filters
    </Button>
  </div>
</div>

// src/components/features/university/UniversityPage/components/mobile-filters.tsx
"use client"

import { Filter } from "lucide-react"
import { Button } from "@/components/ui/react/button"
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/react/sheet"
import { Sidebar } from "./sidebar/sidebar"
import { educationTypes, rankingRanges, type Filters } from "../lib/data"

interface MobileFiltersProps {
  filters: Filters
  onChange: (key: keyof Filters, value: string) => void
  onReset: () => void
  cities?: string[]
}

export function MobileFilters({ filters, onChange, onReset, cities = [] }: MobileFiltersProps) {
  return (
    <div className="flex items-center justify-between md:hidden">
      <h1 className="text-2xl font-bold">Universities</h1>
      <Sheet>
        <SheetTrigger asChild>
          <Button variant="outline" size="icon">
            <Filter className="h-4 w-4" />
            <span className="sr-only">Filter</span>
          </Button>
        </SheetTrigger>
        <SheetContent side="left" className="w-[300px] sm:w-[350px]">
          <div className="py-4">
            <Sidebar filters={filters} onChange={onChange} onReset={onReset} />
          </div>
        </SheetContent>
      </Sheet>
    </div>
  )
}
