// src/components/features/home/OurPartners/components/background-decoration.tsx
export default function BackgroundDecoration() {
  return (
    <div className="absolute inset-0 overflow-hidden pointer-events-none">
      <div className="absolute -top-24 -right-24 w-96 h-96 bg-purple-100 rounded-full opacity-30 blur-3xl"></div>
      <div className="absolute top-1/3 -left-24 w-80 h-80 bg-indigo-100 rounded-full opacity-30 blur-3xl"></div>
      <div className="absolute -bottom-12 right-1/4 w-64 h-64 bg-pink-100 rounded-full opacity-20 blur-3xl"></div>
      <div className="absolute bottom-1/4 left-1/4 w-72 h-72 bg-blue-100 rounded-full opacity-20 blur-3xl"></div>
    </div>
  )
}

// src/components/features/university/UniversityDetailPageSvelte/components/BackgroundDecoration.svelte
<script lang="ts">
  export let className = "";
</script>

<div class={className}>
  <div class="absolute -top-[10%] -right-[15%] w-[60%] h-[60%] bg-blue-500/5 rounded-full blur-3xl" />
  <div class="absolute top-[20%] -left-[10%] w-[50%] h-[60%] bg-indigo-500/5 rounded-full blur-3xl" />
  <div class="absolute bottom-[5%] right-[5%] w-[40%] h-[40%] bg-purple-500/5 rounded-full blur-3xl" />
  <div class="absolute top-[40%] left-[25%] w-[15%] h-[15%] bg-sky-500/10 rounded-full blur-2xl" />
</div>
