// src/components/features/home/SuccessPath/components/background-decoration.tsx
export default function BackgroundDecoration() {
  return (
    <div className="absolute inset-0 overflow-hidden pointer-events-none">
      <div className="absolute -top-24 -right-24 w-96 h-96 bg-blue-100/30 rounded-full blur-3xl"></div>
      <div className="absolute top-1/3 -left-24 w-80 h-80 bg-indigo-100/30 rounded-full blur-3xl"></div>
      <div className="absolute bottom-0 right-1/4 w-64 h-64 bg-yellow-100/20 rounded-full blur-3xl"></div>
      <div className="absolute bottom-1/4 left-1/4 w-72 h-72 bg-blue-100/20 rounded-full blur-3xl"></div>
      
      <div className="absolute inset-0" 
        style={{
          backgroundImage: `
            linear-gradient(0deg, rgba(255,255,255,0.05) 1px, transparent 1px),
            linear-gradient(90deg, rgba(255,255,255,0.05) 1px, transparent 1px)
          `,
          backgroundSize: '50px 50px',
          maskImage: 'radial-gradient(ellipse 80% 80% at 50% 50%, #000 70%, transparent 100%)'
        }}
      ></div>
    </div>
  )
}

// src/components/features/home/OurPartners/components/BackgroundDecoration.svelte
<div class="absolute inset-0 overflow-hidden pointer-events-none">
  <div class="absolute -top-24 -right-24 w-96 h-96 bg-purple-100 rounded-full opacity-30 blur-3xl"></div>
  <div class="absolute top-1/3 -left-24 w-80 h-80 bg-indigo-100 rounded-full opacity-30 blur-3xl"></div>
  <div class="absolute -bottom-12 right-1/4 w-64 h-64 bg-pink-100 rounded-full opacity-20 blur-3xl"></div>
  <div class="absolute bottom-1/4 left-1/4 w-72 h-72 bg-blue-100 rounded-full opacity-20 blur-3xl"></div>
</div>
