// src/components/ui/svelte/Button.svelte
<script lang="ts">
  import { cn } from '@/lib/utils';
  import { buttonTheme } from '@/lib/theme-utils';
  import type { HTMLButtonAttributes } from 'svelte/elements';

  type Variant = 'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link';
  type Size = 'default' | 'sm' | 'lg' | 'icon';

  interface $$Props extends HTMLButtonAttributes {
    variant?: Variant;
    size?: Size;
    class?: string;
    asChild?: boolean;
  }

  export let variant: Variant = 'default';
  export let size: Size = 'default';
  export let type: $$Props['type'] = 'button';
  export let disabled: $$Props['disabled'] = false;
  export let asChild: $$Props['asChild'] = false;

  let className = "";
  export { className as class };
  
  $: classes = cn(
    buttonTheme.base,
    buttonTheme.variant[variant],
    buttonTheme.size[size],
    className
  );
</script>

{#if asChild}
  <slot {className} {disabled} {type} {...$$restProps} />
{:else}
  <button
    {type}
    {disabled}
    class={classes}
    on:click
    {...$$restProps}
  >
    <slot />
  </button>
{/if}

// src/components/ui/react/button.tsx
import * as React from "react"
import { Slot } from "@radix-ui/react-slot"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"
import { buttonTheme } from "@/lib/theme-utils"

const buttonVariants = cva(
  buttonTheme.base,
  {
    variants: {
      variant: {
        default: buttonTheme.variant.default,
        destructive: buttonTheme.variant.destructive,
        outline: buttonTheme.variant.outline,
        secondary: buttonTheme.variant.secondary,
        ghost: buttonTheme.variant.ghost,
        link: buttonTheme.variant.link,
      },
      size: {
        default: buttonTheme.size.default,
        sm: buttonTheme.size.sm,
        lg: buttonTheme.size.lg,
        icon: buttonTheme.size.icon,
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button"
    return (
      <Comp
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    )
  }
)
Button.displayName = "Button"

export { Button, buttonVariants }
