// src/components/ui/react/input.tsx
import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"
import { cn } from "@/lib/utils"
import { inputTheme } from "@/lib/theme-utils"

const inputVariants = cva(
  inputTheme.base,
  {
    variants: {
      variant: {
        default: inputTheme.variant.default,
        destructive: inputTheme.variant.destructive,
        outlined: inputTheme.variant.outlined,
        ghost: inputTheme.variant.ghost,
      },
      size: {
        default: inputTheme.size.default,
        sm: inputTheme.size.sm,
        lg: inputTheme.size.lg,
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

export interface InputProps 
  extends React.InputHTMLAttributes<HTMLInputElement>,
    VariantProps<typeof inputVariants> {}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, type, variant, size, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(inputVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    )
  }
)
Input.displayName = "Input"

export { Input, inputVariants }

// src/components/ui/svelte/Input.svelte
<script lang="ts">
  import { cn } from '../../../lib/utils';
  import { inputTheme } from '../../../lib/theme-utils';
  import type { HTMLInputAttributes } from 'svelte/elements';

  type Variant = 'default' | 'destructive' | 'outlined' | 'ghost';
  type Size = 'default' | 'sm' | 'lg';

  interface $$Props {
    type?: HTMLInputAttributes['type'];
    value?: string;
    placeholder?: string;
    disabled?: boolean;
    variant?: Variant;
    size?: Size;
    class?: string;
  }

  export let type: $$Props['type'] = 'text';
  export let value: string = '';
  export let placeholder: string = '';
  export let disabled: boolean = false;
  export let variant: Variant = 'default';
  export let size: Size = 'default';
  
  let className = "";
  export { className as class };
</script>

<input
  {type}
  class={cn(
    inputTheme.base,
    inputTheme.variant[variant],
    inputTheme.size[size],
    className
  )}
  bind:value
  {placeholder}
  {disabled}
  {...$$restProps}
/>
